#data types
print("data types in python")
print("1. int - integer")
print("2. float - floating point")
print("3. complex - complex numbers")
print("4. str - string")
print("5. bool - boolean")
print("6. list - ordered, mutable collection")
print("7. tuple - ordered, immutable collection")
print("8. set - unordered, unique collection")
print("9. dict - unordered, mutable collection of key-value pairs")
#functions
print("functions in python")
print("1. def - define a function")
print("2. return - return a value from a function")
print("3. lambda - anonymous function")
print("4. map - apply a function to all items in an iterable")
print("5. filter - filter items in an iterable based on a function")
print("6. reduce - apply a function cumulatively to items in an iterable")
print("7. zip - combine multiple iterables into a single iterable")
import math
print("math functions in python")
print("1. math.sqrt() - square root")
print("2. math.pow() - power")
print("3. math.sin() - sine")
print("4. math.cos() - cosine")
print("5. math.tan() - tangent")
print("6. math.log() - logarithm")
print("7. math.exp() - exponential")
print("8. math.factorial() - factorial")
print("9. math.ceil() - round up")
print("10. math.floor() - round down")
print("11. math.pi - pi value")
print("12. math.e - e value")
print("13. math.radians() - convert degrees to radians")
print("14. math.degrees() - convert radians to degrees")
import matplotlib.pyplot as plt
print("matplotlib functions in python")
print("1. plt.plot() - plot data")
print("2. plt.scatter() - scatter plot")
print("3. plt.bar() - bar chart")
print("4. plt.hist() - histogram")
print("5. plt.pie() - pie chart")
print("6. plt.xlabel() - set x-axis label")
print("7. plt.ylabel() - set y-axis label")
print("8. plt.title() - set title")
print("9. plt.legend() - set legend")
print("10. plt.show() - display plot")
print("11. plt.savefig() - save plot to file")
print("12. plt.xlim() - set x-axis limits")
print("13. plt.ylim() - set y-axis limits")
import numpy as np
print("numpy functions in python")
print("1. np.array() - create an array")
print("2. np.zeros() - create an array of zeros")
print("3. np.ones() - create an array of ones")
print("4. np.arange() - create an array of evenly spaced values")
print("5. np.linspace() - create an array of evenly spaced values over a specified interval")
print("6. np.random.rand() - create an array of random values")
print("7. np.random.randint() - create an array of random integers")
print("8. np.reshape() - reshape an array")
print("9. np.transpose() - transpose an array")
print("10. np.concatenate() - concatenate arrays")
print("11. np.split() - split an array into multiple arrays")
print("12. np.mean() - calculate the mean of an array")
print("13. np.median() - calculate the median of an array")
print("14. np.std() - calculate the standard deviation of an array")
print("15. np.sum() - calculate the sum of an array")
print("16. np.min() - calculate the minimum value of an array")
print("17. np.max() - calculate the maximum value of an array")
print("18. np.unique() - find the unique values in an array")
print("19. np.sort() - sort an array")
print("20. np.where() - find the indices of elements that satisfy a condition")
print("21. np.clip() - limit the values in an array to a specified range")
print("22. np.isnan() - check for NaN values in an array")
print("23. np.isinf() - check for infinite values in an array")
import pandas as pd
print("pandas functions in python")
print("1. pd.DataFrame() - create a DataFrame")
print("2. pd.Series() - create a Series")
print("3. pd.read_csv() - read a CSV file into a DataFrame")
print("4. pd.read_excel() - read an Excel file into a DataFrame")
print("5. pd.concat() - concatenate DataFrames")
print("6. pd.merge() - merge DataFrames")
print("7. pd.groupby() - group DataFrame rows")
print("8. pd.pivot_table() - create a pivot table")
print("9. pd.describe() - generate descriptive statistics")
print("10. pd.info() - display information about the DataFrame")
print("11. pd.head() - display the first n rows of the DataFrame")
print("12. pd.tail() - display the last n rows of the DataFrame")
print("13. pd.isnull() - check for missing values in the DataFrame")
print("14. pd.fillna() - fill missing values in the DataFrame")
print("15. pd.dropna() - drop rows with missing values in the DataFrame")